/**
 * Pure, testable Facebook Page posts fetch + sanitization logic shared by the
 * Cloudflare Pages Function and the dev-only Next.js route handler.
 *
 * The Graph API is called server-side so the access token is never exposed to
 * the browser. The same module is used in Node (test runner, Next dev route)
 * and in the Worker runtime (bundled by Wrangler).
 */

const GRAPH_API_BASE = 'https://graph.facebook.com/v21.0';

/**
 * @typedef {{ media_type?: string; title?: string; description?: string; url?: string; media?: { image?: { src?: string }; source?: string } }} Attachment
 * @typedef {{ id: string; message?: string; story?: string; created_time?: string; permalink_url?: string; attachments?: { data?: Attachment[] } }} RawPost
 */

/**
 * Facebook returns post text in different places depending on the post type:
 * - `message`            → regular text posts
 * - `attachments[].description` → photo/video/album captions
 * - `attachments[].title`→ fallback caption for links/media
 * - `story`              → autogenerated summaries ("added 3 new photos")
 * Resolve the best available caption.
 * @param {RawPost} raw
 * @returns {string}
 */
function resolveCaption(raw) {
  const attachment = raw?.attachments?.data?.[0];
  const candidates = [
    raw?.message,
    attachment?.description,
    attachment?.title,
    raw?.story,
  ];
  for (const value of candidates) {
    if (typeof value === 'string' && value.trim()) {
      return value.trim().slice(0, 400);
    }
  }
  return '';
}

/**
 * Resolve the post's primary image URL from its attachments.
 * `full_picture` (the old aggregated field) is deprecated and triggers a
 * #12 error, so we read the image directly from attachments instead.
 * @param {RawPost} raw
 * @returns {string}
 */
function resolvePicture(raw) {
  const media = raw?.attachments?.data?.[0]?.media;
  return media?.image?.src || media?.source || '';
}

/**
 * Sanitize a raw Graph API post into a safe, minimal shape.
 * @param {RawPost} raw
 * @returns {{ id: string; message: string; full_picture: string; permalink_url: string; created_time: string }}
 */
export function sanitizePost(raw) {
  return {
    id: typeof raw?.id === 'string' ? raw.id : '',
    message: resolveCaption(raw),
    full_picture: resolvePicture(raw),
    permalink_url:
      typeof raw?.permalink_url === 'string' ? raw.permalink_url : '',
    created_time:
      typeof raw?.created_time === 'string' ? raw.created_time : '',
  };
}

/**
 * Build the Graph API URL for a page's posts.
 * Uses the non-deprecated `attachments` subfields for images/captions.
 * @param {string} pageId
 * @param {string} accessToken
 * @param {number} limit
 * @returns {string}
 */
export function buildPostsUrl(pageId, accessToken, limit = 10) {
  const fields = [
    'id',
    'message',
    'story',
    'created_time',
    'permalink_url',
    'attachments{media_type,title,description,url,media{image{src},source}}',
  ].join(',');
  const params = new URLSearchParams({
    fields,
    limit: String(limit),
    access_token: accessToken,
  });
  return `${GRAPH_API_BASE}/${encodeURIComponent(pageId)}/posts?${params.toString()}`;
}

/**
 * Fetch and normalize page posts from the Facebook Graph API.
 * @param {string} pageId
 * @param {string} accessToken
 * @param {{ limit?: number; fetchFn?: typeof fetch }} [options]
 * @returns {Promise<{ posts: ReturnType<typeof sanitizePost>[] }>}
 */
export async function fetchPagePosts(pageId, accessToken, options = {}) {
  const { limit = 10, fetchFn = fetch } = options;

  if (!pageId) {
    throw new Error('FACEBOOK_PAGE_ID is not configured.');
  }
  if (!accessToken) {
    throw new Error('FACEBOOK_ACCESS_TOKEN is not configured.');
  }

  const url = buildPostsUrl(pageId, accessToken, limit);
  const res = await fetchFn(url, {
    method: 'GET',
    headers: { 'Content-Type': 'application/json' },
  });

  const body = await res.json().catch(() => ({}));

  if (!res.ok) {
    const fbError = body?.error;
    const detail = fbError
      ? `Facebook API error (${fbError.code || res.status}): ${fbError.message || 'Unknown error'}`
      : `Facebook API returned status ${res.status}.`;
    throw new Error(detail);
  }

  const rawPosts = Array.isArray(body?.data) ? body.data : [];
  const posts = rawPosts
    .map(sanitizePost)
    // Keep any post that has content: a caption, an image, or a permalink.
    // (Filter AFTER sanitizing, since pictures/captions may come from
    // attachments rather than top-level raw fields.)
    .filter((post) => post.id && (post.message || post.full_picture));

  return { posts };
}
